"""tenant account member

Revision ID: 14f30d992bff
Revises: 
Create Date: 2026-03-21 01:03:16.589979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f30d992bff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Identificador da conta do usuário.'),
    sa.Column('name', sa.Text(), nullable=False, comment='Nome completo da conta do usuário.'),
    sa.Column('display_name', sa.Text(), nullable=False, comment='Nome do usuário da conta.'),
    sa.Column('email', sa.Text(), nullable=False, comment='Email da conta do usuário, ligado ao provedor de autenticação.'),
    sa.Column('provider', sa.Text(), nullable=False, comment='Indica qual foi o mecanismo de autenticação utilizado pela conta do usuário (ex.: google auth).'),
    sa.PrimaryKeyConstraint('id'),
    comment='Esté a conta do usuário do sistema.'
    )
    op.create_table('tenant',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Identificador do licenciado.'),
    sa.Column('name', sa.Text(), nullable=False, comment='Nome completo do licenciado.'),
    sa.Column('display_name', sa.Text(), nullable=False, comment='Nome do licenciado.'),
    sa.PrimaryKeyConstraint('id'),
    comment='Este é o licenciado que está contratando o sistema.'
    )
    op.create_table('member',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Identificador do usuário.'),
    sa.Column('name', sa.Text(), nullable=True, comment='Nome completo do usuário.'),
    sa.Column('display_name', sa.Text(), nullable=True, comment='Nome do usuário.'),
    sa.Column('email', sa.Text(), nullable=False, comment='Email do usuário.'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='Ligação do usuário ao licenciado.'),
    sa.Column('account_id', sa.BigInteger(), nullable=True, comment='Ligação do usuário à conta do usuário.'),
    sa.Column('status', sa.Integer(), nullable=False, comment='Situação do usuário:\n1) Ativo\n2) Pendente\n3) Desativado'),
    sa.CheckConstraint('status = 2 OR display_name IS NOT NULL', name='member_display_name_empty'),
    sa.CheckConstraint('status = 2 OR name IS NOT NULL', name='member_name_empty'),
    sa.CheckConstraint('status IN (1, 2, 3)', name='member_status_chk'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Esté o usuário do sistema em um determinado licenciado.'
    )
    op.create_index('member_unique_tenant_account', 'member', ['tenant_id', 'account_id'], unique=True, postgresql_where=sa.text('account_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('member_unique_tenant_account', table_name='member', postgresql_where=sa.text('account_id IS NOT NULL'))
    op.drop_table('member')
    op.drop_table('tenant')
    op.drop_table('account')
    # ### end Alembic commands ###
